export const trendingMovies = [
  "Commando",
  "Predator",
  "Terminator 2: Judgment Day",
  "Die Hard",
  "Rambo: First Blood",
  "The Dark Knight",
  "Inception",
  "Interstellar",
  "Gladiator",
  "Mad Max: Fury Road",
  "John Wick",
  "The Matrix",
  "Avengers: Endgame",
  "Iron Man",
  "Spider-Man: No Way Home",
  "Jurassic Park",
  "Titanic",
  "Avatar",
  "Top Gun: Maverick",
  "Oppenheimer",
];
